---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-nodeport
  labels:
    app: podinfo
spec:
  type: LoadBalancer
  ports:
    - port: 9898
      targetPort: 9898
      protocol: TCP
  selector:
    app: podinfo