apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rainbow-properties
data:
  rainbow.properties: |

    rainbow.master.location.host = 127.0.0.1
    rainbow.deployment.location = 127.0.0.1
    rainbow.master.location.port = 1101
    rainbow.deployment.environment = linux
    rainbow.event.service = eseb
    rainbow.delegate.beaconperiod = 10000
    rainbow.deployment.factory.class = org.sa.rainbow.ports.StandaloneRainbowConnectionFactory

    rainbow.model.number=2
    rainbow.model.path_0=model/target-acme-model.acme
    rainbow.model.load.class_0=org.sa.rainbow.model.acme.commands.KubeCommandFactory
    rainbow.model.name_0=ZNewsSys
    rainbow.model.saveOnClose_0=false

    rainbow.model.path_1=utilities.yaml
    rainbow.model.load.class_1=org.sa.rainbow.model.utility.UtilityCommandFactory
    rainbow.model.name_1=ZNewsSys

    rainbow.model.load.class_2=org.sa.rainbow.model.utility.UtilityHistoryCommandFactory
    rainbow.model.name_2=ZNewsSys
    rainbow.model.saveOnClose_2=false

    rainbow.analyses.size = 1
    rainbow.analyses_0=org.sa.rainbow.evaluator.acme.ArchEvaluator
    rainbow.analyses_1=org.sa.rainbow.evaluator.utility.UtilityEvaluator

    rainbow.adaptation.manager.size=1
    rainbow.adaptation.manager.class_0=org.sa.rainbow.adaptation.AdaptationManager
    rainbow.adaptation.manager.model_0=ZNewsSys:Acme

    rainbow.adaptation.executor.size=1
    rainbow.adaptation.executor.class_0=org.sa.rainbow.stitch.adaptation.StitchExecutor
    rainbow.adaptation.executor.model_0=ZNewsSys:Acme

    rainbow.effector.manager.size=1
    rainbow.effector.manager.class_0=org.sa.rainbow.translator.KubeEffectorManager
    rainbow.effector.manager.model_0=ZNewsSys:Acme

    customize.model.evaluate.period = 2000

    customize.gauges.path = gauges.yaml
    customize.probes.path = probes.yaml
    customize.archop.map.path = op.map
    customize.effectors.path = effectors.yaml

    customize.utility.enabled = false
    customize.scripts.path = stitch
    customize.utility.path = utilities.yaml
    customize.utility.trackStrategy = uSF
    customize.utility.score.minimum.threshold = 0.33
    customize.utility.scenario = scenario 1
    customize.prometheus.url=http://prometheus:9090
